theme: jekyll-theme-minimal
title: biography
description: Things happened in my life.
navigation:
  - title: poetry
    url: https://zenkarsha.github.io/poetry/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
  - title: favorite
    url: https://zenkarsha.github.io/favorite/
  - title: works
    url: https://zenkarsha.github.io/works/
  - title: blog
    url: https://zenkarsha.github.io/blog/
  - title: twitter
    url: https://twitter.com/zenkarsha/

