theme: jekyll-theme-minimal
title: biography
description: Something happened in my life.
navigation:
  - title: biography
    url: https://zenkarsha.github.io/biography/
  - title: poetry
    url: https://zenkarsha.github.io/poetry/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
